server:
    port: 8080
    forward-headers-strategy: framework
spring:
    application:
        name: ms-citizens
    data:
        mongodb:
            uri: ${CITIZENS_MONGODB_URI}
    jackson:
        default-property-inclusion: non_default
        property-naming-strategy: SNAKE_CASE
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL}/eureka
springdoc:
    cache:
        disabled: true
